default: &default
  adapter: postgresql
  pool: 5

development:
  <<: *default
  database: your_app_development

test:
  <<: *default
  database: your_app_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>